import js from '@eslint/js';

// Lints the JavaScript this project owns: build and test tooling, plus the
// window scripts not yet ported to TypeScript. Everything vendored or
// generated is ignored — findings there are not ours to act on, and Mousetrap
// in particular is deliberately kept diffable against upstream.
export default [
    {
        ignores: [
            'node_modules/**', 'deploy/core/node_modules/**', 'deploy/plugins/**',
            'src-gen/**', 'builds/**',
            // Generated by shadow-cljs or tsc.
            'deploy/core/lighttable/bootstrap.js',
            'deploy/core/lighttable/user.js',
            'deploy/core/lighttable/paredit.js',
            'deploy/core/lighttable/background/worker.js',
            'deploy/core/main.js', 'deploy/core/preload.js',
            'deploy/core/browserInjection.js', 'deploy/core/window/**',
            'plugins/**/*_compiled.js',
            // Vendored: Mousetrap, kept diffable against upstream.
            'deploy/core/lighttable/util/keyevents.js'
        ]
    },
    {
        files: ['script/**/*.js', 'deploy/core/lighttable/**/*.js'],
        ...js.configs.recommended,
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                require: 'readonly', module: 'writable', exports: 'writable',
                process: 'readonly', __dirname: 'readonly', console: 'readonly',
                Buffer: 'readonly', fetch: 'readonly', WebSocket: 'readonly',
                setTimeout: 'readonly', clearTimeout: 'readonly',
                setInterval: 'readonly', clearInterval: 'readonly',
                window: 'readonly', document: 'readonly', navigator: 'readonly',
                performance: 'readonly', lt: 'readonly', CodeMirror: 'readonly',
                define: 'readonly',
                // ws.js is served to connecting browsers, not run here.
                io: 'readonly', cljs: 'readonly', lttools: 'writable',
                jQuery: 'readonly', Element: 'readonly'
            }
        },
        rules: {
            ...js.configs.recommended.rules,
            // Unused arguments are how callback signatures document themselves.
            'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
            // `catch (e) {}` is deliberate in several probes: the failure is
            // the answer.
            'no-empty': ['error', { allowEmptyCatch: true }],
            // Pre-existing var redeclaration in scripts that predate this
            // work. Worth seeing, not worth blocking on.
            'no-redeclare': 'warn',
            'no-useless-assignment': 'warn',
            eqeqeq: 'off'
        }
    }
];
