// Storybook's story files, written from the ClojureScript registry.
//
// Storybook indexes stories by finding files and reading their exports, one
// default export per component. That is a real constraint and there is no
// arguing with it — so the files exist, and nothing about them is a decision:
// every one is this script's output from `lt.ui.story/registry`.
//
// They are **not committed**, and that is a change from what module 1's
// documentation said it would do. The comparison was `doc/api`, which is
// generated and committed and guarded by `make check` — but `doc/api` is
// committed because people read it on GitHub, and a diff of it says what
// changed about the promised API. Nobody reads these. A generated file nobody
// reads, committed, is a thing that can go stale and a check that has to exist
// to notice; generated into a gitignored directory by the same command that
// runs Storybook, it cannot.

import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = path.join(import.meta.dirname, '..');
const OUT = path.join(ROOT, '.storybook', 'stories');
const MANIFEST = path.join(ROOT, 'target', 'stories-manifest.js');

interface Story { id: string; title: string; name: string; doc: string | null; props: string }

if (!fs.existsSync(MANIFEST)) {
    console.error(`No ${path.relative(ROOT, MANIFEST)} — run \`shadow-cljs compile stories-manifest\`.`);
    process.exit(1);
}

const stories = JSON.parse(
    execFileSync(process.execPath, [MANIFEST], { encoding: 'utf8' })) as Story[];

/** A story's export name: `shutting-down` → `ShuttingDown`. */
function exportName(name: string): string {
    const pascal = name.split(/[^a-zA-Z0-9]+/).filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
    // A CSF export has to be a JavaScript identifier, and a state named for a
    // number would not be one.
    return /^[A-Za-z]/.test(pascal) ? pascal : `State${pascal}`;
}

/** Where a component's file goes: `Kit/chrome/status-dot` → `chrome/status-dot`. */
function fileFor(title: string): string {
    return title.replace(/^Kit\//, '') + '.stories.js';
}

const byTitle = new Map<string, Story[]>();
for (const story of stories) {
    const list = byTitle.get(story.title) ?? [];
    list.push(story);
    byTitle.set(story.title, list);
}

// Rewritten from scratch every run: a component that loses a state should lose
// its file, and a stale file is a story in the sidebar that renders nothing.
fs.rmSync(OUT, { recursive: true, force: true });

let count = 0;
for (const [title, group] of byTitle) {
    const file = path.join(OUT, fileFor(title));
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const up = path.relative(path.dirname(file), path.join(OUT, '..', 'generated', 'kit.js'));

    const lines = [
        '// Generated by script/gen-stories.mts from lt.ui.story/registry.',
        '// Not committed, not edited — see doc/storybook.md.',
        `import { render } from '${up.startsWith('.') ? up : './' + up}';`,
        '',
        'export default {',
        `    title: ${JSON.stringify(title)},`,
        ...(group[0]!.doc
            ? [`    parameters: { docs: { description: { component: ${
                JSON.stringify(group[0]!.doc.replace(/\s+/g, ' ').trim())} } } },`]
            : []),
        '};',
        ''
    ];
    for (const story of group) {
        lines.push(`// props: ${story.props}`);
        lines.push(`export const ${exportName(story.name)} = {`);
        lines.push(`    name: ${JSON.stringify(story.name)},`);
        lines.push(`    render: () => render(${JSON.stringify(story.id)}),`);
        lines.push('};');
        count++;
    }
    fs.writeFileSync(file, lines.join('\n') + '\n');
}

console.log(`  ok   ${count} stories in ${byTitle.size} files`);
